set nocompatible
filetype off
set mmp=5000
"set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
set rtp+=~/setup/files/vim/snippets/
call vundle#begin()
runtime macros/matchit.vim

"fuzzy finder
set rtp+=/usr/local/opt/fzf

"let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" Syntax
Plugin 'tmux-plugins/vim-tmux'
Plugin 'vimwiki/vimwiki'
Plugin 'tpope/vim-commentary'

Plugin 'othree/html5.vim'
Plugin 'tpope/vim-haml'
Plugin 'tpope/vim-markdown'

Plugin 'hail2u/vim-css3-syntax'
Plugin 'cakebaker/scss-syntax.vim'

Plugin 'pangloss/vim-javascript'
Plugin 'othree/yajs'
Plugin 'mxw/vim-jsx'
Plugin 'fleischie/vim-styled-components'
Plugin 'isRuslan/vim-es6'
Plugin 'ternjs/tern_for_vim'

Plugin 'tpope/vim-rails'
Plugin 'thoughtbot/vim-rspec'

Plugin 'stephpy/vim-yaml'

"AutoComplete
if has('nvim')
  Plugin 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
else
  Plugin 'Shougo/deoplete.nvim'
  Plugin 'roxma/nvim-yarp'
  Plugin 'roxma/vim-hug-neovim-rpc'
endif
let g:deoplete#enable_at_startup = 1


"file helpers
Plugin 'dense-analysis/ale'
Plugin 'pechorin/any-jump.vim'
Plugin 'tpope/vim-surround'

" Tags
Plugin 'ludovicchabant/vim-gutentags'

"Send commands
Plugin 'jgdavey/tslime.vim'
Plugin 'skywind3000/asyncrun.vim'

"Math
Plugin 'sk1418/HowMuch'

"Basic Helpers
Plugin 'Yggdroot/indentLine'
Plugin 'scrooloose/nerdtree'
Plugin 'ervandew/supertab'
Plugin 'majutsushi/tagbar'

"Snippets
Plugin 'MarcWeber/vim-addon-mw-utils'
Plugin 'tomtom/tlib_vim'
Plugin 'garbas/vim-snipmate'
Plugin 'honza/vim-snippets'

"Search
Plugin 'rking/ag.vim'
Plugin 'junegunn/fzf.vim'

"Other
Plugin 'morhetz/gruvbox'
Plugin 'tpope/vim-fugitive'
Plugin 'rgarver/Kwbd.vim'

call vundle#end()
filetype plugin indent on
syntax enable

"SOURCE
nmap <leader>so :source $MYVIMRC<CR>

"GENERAL
set backspace=2
set splitbelow
set splitright

"Zoom
noremap Zz <c-w>_ \| <c-w>\|
noremap Zo <c-w>=

"syntax/linting
syntax on
filetype plugin on
filetype plugin indent on
au BufRead,BufNewFile *.scss set filetype=scss
set textwidth=80

" formatters
au FileType javascript setlocal formatprg=prettier
au FileType javascript.jsx setlocal formatprg=prettier
au FileType typescript setlocal formatprg=prettier\ --parser\ typescript
au FileType html setlocal formatprg=js-beautify\ --type\ html
au FileType scss setlocal formatprg=prettier\ --parser\ css
au FileType css setlocal formatprg=prettier\ --parser\ css


" linting and AutoComplete
let g:ale_set_loclist = 0
let g:ale_set_quickfix = 1
nmap <C-k> <Plug>(ale_previous_wrap)
nmap <C-j> <Plug>(ale_next_wrap)
let g:ale_set_loclist = 0
let g:ale_set_quickfix = 1
let g:ale_sign_column_always = 1

let g:ale_linters = {
\ 'python': ['flake8', 'pylint'],
\ 'javascript': ['eslint'],
\ 'vue': ['eslint']
\}

let g:ale_fixers = {
\  'javascript': ['eslint'],
\  'typescript': ['prettier', 'tslint'],
\  'vue': ['eslint'],
\  'scss': ['prettier'],
\  'html': ['prettier'],
\  'reason': ['refmt']
\}
let g:ale_fix_on_save = 1

let g:tern_request_timeout = 1
let g:tern_request_timeout = 6000

"STATUS LINE
" always display status line
set laststatus=2

" clear the statusline for when vimrc is reloaded
set statusline=   
" buffer number
set statusline+=%-3.3n\                       
" flags
set statusline+=%h%m%r%w                      
" file name
set statusline+=%t\                           

" right align
set statusline+=%=
" line:column
set statusline+=%l:%c\ 
"start file meta group
set statusline+=[
" filetype
set statusline+=%{strlen(&ft)?&ft:'none'},   
" encoding
set statusline+=%{strlen(&fenc)?&fenc:&enc},  
" end file meta group
set statusline+=]\ 

" enable eslint
let g:syntastic_javascript_checkers = ['eslint']


" force json files to use json linting instead of javascript
au BufRead,BufNewFile *.json set filetype=json

" run specs in tmux pane
let g:rspec_command = 'call Send_to_Tmux("bin/rspec {spec}\n")'
map <Leader>s :call RunNearestSpec()<CR>
nmap <Leader>rs <Plug>SetTmuxVars

"window
set number
set expandtab tabstop=2 shiftwidth=2 softtabstop=2
set gfn=monaco:h12

"swp and backup
set dir=~/.vimtmp
set backup
set backupdir=~/.vimbackup

"cursor
set cursorline
set cursorcolumn

"KEYMAPPING
nmap <Tab> <leader>

"navigation
nmap j gj
nmap k gk

"buffers
nmap <leader>bd :Kwbd<CR>
nmap <leader>vs :vsplit<CR>
nmap <leader>hs :split<CR>
nmap <C-L> <C-W>l
nmap <C-H> <C-W>h
nmap <C-J> <C-W>j
nmap <C-K> <C-W>k

"FZF
nnoremap <leader>d :Buffers<CR>
nmap <leader>f :Files<CR>

"registers
nmap <leader>" :reg<CR>

"search
set incsearch
set ignorecase
set smartcase
set hlsearch
nmap <leader>q :nohlsearch<CR>

" The Silver Searcher
if executable('ag')
  " Use ag over grep
  set grepprg=ag\ --nogroup\ --nocolor
endif

" bind K to grep word under cursor
nnoremap K :grep! "\b<C-R><C-W>\b"<CR>:cw<CR>

"nerdtree
nnoremap <leader>e :NERDTreeToggle<CR>

"Gundo
map <leader>gut :GundoToggle<CR>

"CloseTag.vim
let b:unaryTagsStack=""
if !exists("b:unaryTagsStack")
    let b:unaryTagsStack=""
endif

"Snippets
let g:snipMate = get(g:, 'snipMate', {}) " Allow for vimrc re-sourcing
let g:snipMate.snippet_version = 1
let g:snipMate.scope_aliases = {}
let g:snipMate.scope_aliases['ruby'] = 'ruby,rails'

" Wikis
let g:vimwiki_list = [
  \ {'path': '~/Sync/wikis/personal', 'path_html': '~/Sync/wikis/personal/html'},
  \ {'path': '~/Sync/wikis/projects', 'path_html': '~/Sync/wikis/projects/html'},
  \ {'path': '~/Sync/wikis/marie', 'path_html': '~/Sync/wikis/marie/html'}
  \ ]

let vimwiki_folding = 'list'
setlocal foldmethod=syntax

" insert date
nmap <leader>id :put =strftime('%b %d, %Y')

"NERDREE
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif
let NERDChristmasTree=1
let NERDTreeWinSize=40

"COLORS
set t_Co=256
set background=dark
colorscheme gruvbox

"RESIZING
if bufwinnr(1)
  map + <C-W>+
  map - <C-W>-
endif

"PASTE
set pastetoggle=<leader>p

"Thyme
nmap <leader>0 :silent execute "!thyme -d"<cr>

"Rails
nnoremap <Leader>b :TagbarToggle<CR>
