set nocompatible
filetype off
set mmp=5000
"set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
set rtp+=~/setup/files/vim/snippets/
call vundle#begin()
runtime macros/matchit.vim

"fuzzy finder
set rtp+=/usr/local/opt/fzf

"let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" My plugins
" Syntax
Plugin 'tpope/vim-markdown'
Plugin 'othree/html5.vim'
Plugin 'tpope/vim-haml'
Plugin 'fleischie/vim-styled-components'
Plugin 'hail2u/vim-css3-syntax'
Plugin 'cakebaker/scss-syntax.vim'
Plugin 'pangloss/vim-javascript'
Plugin 'mxw/vim-jsx'
Plugin 'vim-syntastic/syntastic'
Plugin 'tpope/vim-rails'
Plugin 'isRuslan/vim-es6'
Plugin 'tmux-plugins/vim-tmux'
Plugin 'thoughtbot/vim-rspec'
Plugin 'jgdavey/tslime.vim'
Plugin 'vimwiki/vimwiki'
Plugin 'pechorin/any-jump.vim'

"Helpers
Plugin 'sjl/gundo.vim'
Plugin 'Yggdroot/indentLine'
Plugin 'scrooloose/nerdtree'
Plugin 'scrooloose/nerdcommenter'
Plugin 'ervandew/supertab'
Plugin 'majutsushi/tagbar'

"Snippets
Plugin 'MarcWeber/vim-addon-mw-utils'
Plugin 'tomtom/tlib_vim'
Plugin 'garbas/vim-snipmate'
Plugin 'honza/vim-snippets'

"Search
Plugin 'rking/ag.vim'
Plugin 'junegunn/fzf.vim'

"Other
Plugin 'morhetz/gruvbox'
Plugin 'tpope/vim-fugitive'
Plugin 'Lokaltog/vim-powerline'
Plugin 'tpope/vim-surround'
Plugin 'rgarver/Kwbd.vim'
Plugin 'zenburn'
Plugin 'blindFS/vim-taskwarrior'

call vundle#end()
filetype plugin indent on
syntax enable

"SOURCE
nmap <leader>s :source $MYVIMRC<CR>

"GENERAL
set backspace=2
set splitbelow
set splitright

"Zoom
noremap Zz <c-w>_ \| <c-w>\|
noremap Zo <c-w>=

"syntax/linting
syntax on
filetype plugin on
filetype plugin indent on
au BufRead,BufNewFile *.scss set filetype=scss
set textwidth=80

" syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
set statusline+=%{FugitiveStatusline()}

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 0
let g:syntastic_check_on_wq = 0

nmap <leader>st :SyntasticToggleMode<CR>
nmap <leader>sc :SyntasticCheck<CR>
nmap <leader>sf :SyntasticCheck --fix<CR>

" enable eslint
let g:syntastic_javascript_checkers = ['eslint']


" force json files to use json linting instead of javascript
au BufRead,BufNewFile *.json set filetype=json

" run specs in tmux pane
let g:rspec_command = 'call Send_to_Tmux("bin/rspec {spec}\n")'
" vim-rspec mappings
map <Leader>t :call RunCurrentSpecFile()<CR>
map <Leader>s :call RunNearestSpec()<CR>
map <Leader>l :call RunLastSpec()<CR>
map <Leader>a :call RunAllSpecs()<CR>
nmap <Leader>rs <Plug>SetTmuxVars

"window
set number
set expandtab tabstop=2 shiftwidth=2 softtabstop=2
set gfn=monaco:h12

"swp and backup
set dir=~/.vimtmp
set backup
set backupdir=~/.vimbackup

"cursor
set cursorline
set cursorcolumn
"status bar
set laststatus=2

"KEYMAPPING
nmap <Tab> <leader>

"navigation
nmap j gj
nmap k gk

"buffers
nmap <leader>bd :Kwbd<CR>
nmap <leader>vs :vsplit<CR>
nmap <leader>hs :split<CR>
nmap <C-L> <C-W>l
nmap <C-H> <C-W>h
nmap <C-J> <C-W>j
nmap <C-K> <C-W>k

"FZF
nmap ;; :Buffers<CR>
nmap '' :Files<CR>

"registers
nmap <leader>" :reg<CR>

"search
set incsearch
set ignorecase
set smartcase
set hlsearch
nmap <leader>q :nohlsearch<CR>

" The Silver Searcher
if executable('ag')
  " Use ag over grep
  set grepprg=ag\ --nogroup\ --nocolor
endif

" bind K to grep word under cursor
nnoremap K :grep! "\b<C-R><C-W>\b"<CR>:cw<CR>

"nerdtree
nnoremap <leader>e :NERDTreeToggle<CR>

"markdown
nmap <leader>dm :%!/usr/local/bin/markdown --html4tags<CR>

"Gundo
map <leader>gut :GundoToggle<CR>

"CloseTag.vim
let b:unaryTagsStack=""
if !exists("b:unaryTagsStack")
    let b:unaryTagsStack=""
endif

"Snippets
let g:snipMate = get(g:, 'snipMate', {}) " Allow for vimrc re-sourcing
let g:snipMate.snippet_version = 1
let g:snipMate.scope_aliases = {}
let g:snipMate.scope_aliases['ruby'] = 'ruby,rails'

" Wiki
let g:vimwiki_list = [{'path': '~/setup/wiki/',
                      \ 'path_html': '~/setup/wiki/wiki_html'}]
" insert date
nmap <leader>id :put =strftime('%b %d, %Y')<CR>

"NERDREE
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif
let NERDChristmasTree=1
let NERDTreeWinSize=40

"COLORS
set t_Co=256
set background=dark
colorscheme gruvbox

"RESIZING
if bufwinnr(1)
  map + <C-W>+
  map - <C-W>-
endif

"PASTE
set pastetoggle=<leader>p

"Thyme
nmap <leader>0:!thyme -d<cr>

"Rails
nnoremap <Leader>b :TagbarToggle<CR>
