# Antigen
source ~/.zsh/antigen.zsh
antigen use oh-my-zsh

antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle git@github.com:spwhitt/nix-zsh-completions.git

antigen apply
plugins=(git heroku pip lein command-not-found tmux)

# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh
fpath=(/usr/local/share/zsh-completions $fpath)
setopt autocd

# Uncomment following line if you want red dots to be displayed while waiting for completion
 COMPLETION_WAITING_DOTS="true"

# Customize PATH
path=(
  /usr/local/bin
  /usr/bin
  /bin
  /usr/sbin
  /sbin
  /opt/X11/bin
  /usr/local/MacGPG2/bin
  /usr/local/share/
  $HOME/.cargo/env
  $HOME/.cargo/bin
)

export PATH=$path:$PATH

##Tokens
export PASSWORD_STORE_DIR=~/.tokens/pass
export GNUPGHOME=~/.tokens/gnupg

# Editor
export EDITOR='vim'
alias vim='nvim'

fpath=($fpath /usr/local/share/doc/task/scripts/zsh)
autoload -Uz compinit
compinit

#bookbub
export BBWORKSPACE=~/code/bb
export INTERNAL_API_USERNAME_STAGING="bookbub"

# marks
export MARKPATH=$HOME/.marks
function jump { 
  cd -P "$MARKPATH/$1" 2>/dev/null || echo "No such mark: $1"
}
function mark { 
  mkdir -p "$MARKPATH"; ln -s "$(pwd)" "$MARKPATH/$1"
}
function unmark { 
  rm -i "$MARKPATH/$1"
}
function marks {
  \ls -l "$MARKPATH" | tail -n +2 | sed 's/  / /g' | cut -d' ' -f9- | awk -F ' -> ' '{printf "%-10s -> %s\n", $1, $2}'
}
alias j='jump'

## Aliases
# For Easy Editing
alias zconf='vim ~/.zshrc && source ~/.zshrc'
alias bashconf='vim ~/.bash_profile'
alias sshconf='vim ~/.ssh/config'
alias vimconf='vim ~/.vimrc'
alias tconf='vim ~/.tmux.conf && tmux source-file ~/.tmux.conf'
alias aconf='vim ~/.config/alacritty/alacritty.yml'
alias re-source='source ~/.zshrc && source ~/.tmux.conf && source ~/.config/alacritty/alacritty.yml'

# Time Trackin
alias wat='watson'

# Navigation
alias code='cd ~/code'

# LS
alias ll='ls -alp'
alias ls='ls -G'
alias sl='sl'

#Eject all disks
alias eject='osascript -e "tell application \"Finder\" to eject (every disk whose ejectable is true)"'

# Open Apps
alias shop='open -b com.adobe.Photoshop'

# Rails
alias rs='bin/rails server'
alias rake='bin/rake'
alias rc='rails console'

#Docker
alias dc='docker-compose'
alias dm='docker-machine'
de () { eval $(docker-machine env $1) }

# Git Stuff
alias gs='git status'
alias gc='git commit'
alias gcam='git commit -am'
alias gp='git push'
#clean up stale local branches
alias gitcleanup="git remote prune origin && git branch -vv | awk '/origin.*: gone/ {print \$1}' | fold -s | xargs -p git branch -D"
alias git-sorted="git madge sorted --basedir . --webpack-config make_webpack_config.js src"
alias git-depgraph="git madge image --basedir . --webpack-config make_webpack_config.js src | imgcat"

# Remove spaces and swap with underscores in current directory
alias rmspaces='rename "s/ /_/g" *'

# Navigation
alias notes='tmux a -t notes'
alias lello='tmux a -t lello'

# PS aux grep
alias psag='ps aux | grep'

# Simulators
alias sim='open -n /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app'

#Weather
function wttr {
 curl wttr.in/$1
}

## Prompt
# Global Options
setopt prompt_subst
autoload colors zsh/terminfo
autoload -U colors && colors # Enable colors in prompt
force_colored_prompt=yes
color_prompt=yes

## Git Stuff

source ~/.zsh/zsh-git-prompt/zshrc.sh

ZSH_THEME_GIT_PROMPT_PREFIX="%K{39}%F{235} "
ZSH_THEME_GIT_PROMPT_SUFFIX="%F{235}%K{39} %F{39}%K{235}"
ZSH_THEME_GIT_PROMPT_SEPARATOR="%F{39}%K{235}%F{235}%K{39} "
ZSH_THEME_GIT_PROMPT_BRANCH="%F{235}%K{39}"
ZSH_THEME_GIT_PROMPT_STAGED="%F{15}%K{39}●%G"
ZSH_THEME_GIT_PROMPT_CONFLICTS="%F{15}%K{39} x%G"
ZSH_THEME_GIT_PROMPT_CHANGED="%F{15}%K{39} +%G"
ZSH_THEME_GIT_PROMPT_BEHIND="%F{15}%K{39} ↓%G"
ZSH_THEME_GIT_PROMPT_AHEAD="%F{15}%K{39} ↑%G"
ZSH_THEME_GIT_PROMPT_UNTRACKED="%F{15}%K{39} …%G"
ZSH_THEME_GIT_PROMPT_CLEAN="%F{15}%K{39}✔%G"


#Set Prompt
set_prompt() {

  myjobs=()
  for a (${(k)jobstates})
  {j=$jobstates[$a];i="${${(@s,:,)j}[2]}"
  myjobs+=($a${i//[^+-]/})}
  myjobs=${(j:,:)myjobs}

  rehash

  RPS1='$myjobs'
  PS1='
%F{235}%K{235}\
%F{215}%d\
%F{235}%K{235}\
$(git_super_status)
%F{9}%K{235}  %c
%F{215}  ➜  %{$reset_color%}%K{235}'
}

precmd () {
set_prompt
}

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"


export GOPATH=$HOME/golang
export GOROOT=/usr/local/opt/go/libexec
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$GOROOT/bin

#Nix
source ~/.nix-profile/etc/profile.d/nix.sh
export NIX_PATH=$NIX_PATH:bbpkgs=https://github.com/BookBub/nixpkgs/archive/19.07.0.1.tar.gz
prompt_nix_shell_setup
export ADMIN=true

brew-token () {
export HOMEBREW_GITHUB_API_TOKEN=$(pass show homebrew.github.api.token)
}

eval "$(direnv hook zsh)"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
